# Stages:
# 0. guix pull
# 1. guix build
stages:
  - update
  - build

##########################
# Stage 0: Guix update   #
##########################
update:
  stage: update
  script:
    - echo "(cons (channel (name 'guix-hpc) (url \"https://gitlab.inria.fr/guix-hpc/guix-hpc.git\")) %default-channels)" > hpc-channels.scm
    - mkdir -p .channels
    - guix pull -C hpc-channels.scm -p .channels/guix-hpc

  # Share the .channels/ directory with subsequent jobs.
  # Note: Call it '.channels' to ensure 'guix build' below won't attempt
  # to traverse it.
  artifacts:
    paths:
      - .channels/

###########################
# Stage 1: Build packages #
###########################
starpu_cuda:
  stage: build
  script:
    - .channels/guix-hpc/bin/guix describe
    - .channels/guix-hpc/bin/guix build -L . starpu-cuda

chameleon_cuda:
  stage: build
  script:
    - .channels/guix-hpc/bin/guix describe
    - .channels/guix-hpc/bin/guix build -L . chameleon-cuda

chameleon_mkl_mt:
  stage: build
  script:
    - .channels/guix-hpc/bin/guix describe
    - .channels/guix-hpc/bin/guix build -L . chameleon-mkl-mt

chameleon_cuda_mkl_mt:
  stage: build
  script:
    - .channels/guix-hpc/bin/guix describe
    - .channels/guix-hpc/bin/guix build -L . chameleon-cuda-mkl-mt

mumps_mkl:
  stage: build
  script:
    - .channels/guix-hpc/bin/guix describe
    - .channels/guix-hpc/bin/guix build -L . mumps-mkl

mumps_mkl_metis:
  stage: build
  script:
    - .channels/guix-hpc/bin/guix describe
    - .channels/guix-hpc/bin/guix build -L . mumps-mkl-metis

mumps_mkl_openmpi:
  stage: build
  script:
    - .channels/guix-hpc/bin/guix describe
    - .channels/guix-hpc/bin/guix build -L . mumps-mkl-openmpi

mumps_mkl_metis_openmpi:
  stage: build
  script:
    - .channels/guix-hpc/bin/guix describe
    - .channels/guix-hpc/bin/guix build -L . mumps-mkl-metis-openmpi

pastix_5_mkl:
  stage: build
  script:
    - .channels/guix-hpc/bin/guix describe
    - .channels/guix-hpc/bin/guix build -L . pastix-5-mkl
