# Stages:
# 0. guix pull
# 1. guix build
stages:
  - update
  - build

##########################
# Stage 0: Guix update   #
##########################
update:
  stage: update
  script:
    - echo "(cons (channel (name 'guix-hpc) (url \"https://gitlab.inria.fr/guix-hpc/guix-hpc.git\")) %default-channels)" > hpc-channels.scm
    - mkdir -p channels
    - guix pull -C hpc-channels.scm -p channels/guix-hpc

  # Share the channels/ directory with subsequent jobs.
  artifacts:
    paths:
      - channels/

###########################
# Stage 1: Build packages #
###########################
starpu_cuda:
  stage: build
  script:
    - channels/guix-hpc/bin/guix build -L . starpu-cuda
